/*
 * Copyright 2016 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.nbgames.hekaton;

import org.nbgames.core.api.DictNbg;
import org.nbgames.core.api.ui.NewGamePanel;

/**
 *
 * @author Patrik Karlsson
 */
public class HekatonNewGamePanel extends NewGamePanel {

    private final Options mOptions = Options.getInstance();

    /**
     * Creates new form HekatonNewGamePanel
     */
    public HekatonNewGamePanel() {
        initComponents();
    }

    @Override
    public void load() {
        selectPlayersPanel.setNumOfPlayers(mOptions.getNumOfPlayers());
        selectPlayersPanel.restoreSelection(getClass());
        goalSpinner.setValue(mOptions.getGoal());
        twoDiceCheckBox.setSelected(mOptions.isTwoDice());
        bigPigCheckBox.setSelected(mOptions.isBigPig());
    }

    @Override
    public void save() {
        mOptions.setNumOfPlayers(selectPlayersPanel.getNumOfPlayers());
        selectPlayersPanel.saveSelection(getClass());
        mOptions.setPlayers(selectPlayersPanel.getPlayers());
        mOptions.setGoal((Integer) goalSpinner.getValue());
        mOptions.setTwoDice(twoDiceCheckBox.isSelected());
        mOptions.setBigPig(bigPigCheckBox.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        variantLabel = new javax.swing.JLabel();
        goalLabel = new javax.swing.JLabel();
        goalSpinner = new javax.swing.JSpinner();
        twoDiceCheckBox = new javax.swing.JCheckBox();
        bigPigCheckBox = new javax.swing.JCheckBox();
        selectPlayersPanel = new org.nbgames.core.api.ui.SelectPlayersPanel();

        variantLabel.setFont(variantLabel.getFont().deriveFont(variantLabel.getFont().getStyle() | java.awt.Font.BOLD, variantLabel.getFont().getSize()+4));
        variantLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        variantLabel.setText(DictNbg.VARIANT.toString());

        goalLabel.setText(DictNbg.GOAL.toString());

        goalSpinner.setModel(new javax.swing.SpinnerNumberModel(100, 2, 1000, 1));

        twoDiceCheckBox.setText(org.openide.util.NbBundle.getMessage(HekatonNewGamePanel.class, "HekatonNewGamePanel.twoDiceCheckBox.text")); // NOI18N

        bigPigCheckBox.setText(org.openide.util.NbBundle.getMessage(HekatonNewGamePanel.class, "HekatonNewGamePanel.bigPigCheckBox.text")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, twoDiceCheckBox, org.jdesktop.beansbinding.ELProperty.create("${selected}"), bigPigCheckBox, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        selectPlayersPanel.setMaxNumOfPlayers(6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectPlayersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .addComponent(variantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goalLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(goalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(twoDiceCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bigPigCheckBox)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(variantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goalLabel)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoDiceCheckBox)
                    .addComponent(bigPigCheckBox))
                .addGap(18, 18, 18)
                .addComponent(selectPlayersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bigPigCheckBox;
    private javax.swing.JLabel goalLabel;
    private javax.swing.JSpinner goalSpinner;
    private org.nbgames.core.api.ui.SelectPlayersPanel selectPlayersPanel;
    private javax.swing.JCheckBox twoDiceCheckBox;
    private javax.swing.JLabel variantLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
