/*
 * Copyright 2016 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.nbgames.hekaton;

import org.nbgames.core.api.ui.NewGamePanel;

/**
 *
 * @author Patrik Karlsson
 */
public class HekatonNewGamePanel extends NewGamePanel {

    private final Options mOptions = Options.getInstance();

    /**
     * Creates new form HekatonNewGamePanel
     */
    public HekatonNewGamePanel() {
        initComponents();
    }

    @Override
    public void load() {
        selectPlayersPanel.setNumOfPlayers(mOptions.getNumOfPlayers());
        selectPlayersPanel.restoreSelection(getClass());
    }

    @Override
    public void save() {
        mOptions.setNumOfPlayers(selectPlayersPanel.getNumOfPlayers());
        selectPlayersPanel.saveSelection(getClass());
        mOptions.setPlayers(selectPlayersPanel.getPlayers());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectPlayersPanel = new org.nbgames.core.api.ui.SelectPlayersPanel();

        selectPlayersPanel.setMaxNumOfPlayers(6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectPlayersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectPlayersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.nbgames.core.api.ui.SelectPlayersPanel selectPlayersPanel;
    // End of variables declaration//GEN-END:variables
}
